spring.application.name=spring-ai-tools-calling
spring.ai.google.genai.api-key=AIzaSyDjtxyltQ_MB8blJycnK8eXfo45R435Yi8
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.base-url=https://generativelanguage.googleapis.com
server.port=8081