package com.Mrpal.demo.controller;

import com.Mrpal.demo.service.HrAssistantService;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import reactor.core.publisher.Flux;

@RestController
public class HrController {

    private final HrAssistantService hrService;

    public HrController(HrAssistantService hrService) {
        this.hrService = hrService;
    }

    /**
     * Standard Request-Response.
     * Use this for shorter answers where waiting 2-3 seconds is okay.
     */
    @GetMapping("/ask")
    public String ask(@RequestParam(value = "message", defaultValue = "How can you help me?") String message) {
        return hrService.askQuestion(message);
    }

    /**
     * Streaming Response.
     * Returns characters as they are generated by Gemini.
     * Accessible at: http://localhost:8080/stream?message=Explain leave policy
     */
    @GetMapping(value = "/stream", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
    public Flux<String> stream(@RequestParam(value = "message") String message) {
        return hrService.streamQuestion(message);
    }
}